### ISSUE TITLE
Documentation for options in rama_py

### ISSUE THREAD

**Issue by constantinpape** [pawelswoboda/RAMA#21]
The `multicut_solver_options` class has two constructors, one without parameters and one with a lot of parameters, 
see https://github.com/pawelswoboda/RAMA/blob/master/src/rama_py.cpp#L15-L17.

It would be nice to document this a bit, especially how it relates to the parameters mentioned in the README: https://github.com/pawelswoboda/RAMA#parameters.

Which parameters determine the trade-off between speed and accuracy?

**Comment by aabbas90** [comment]
Good point. I have added another constructor for this purpose in python interface and described it in [readme](https://github.com/pawelswoboda/RAMA#python-solver).

**Comment by constantinpape** [comment]
That's very helpful, thanks!
