### ISSUE TITLE
Cannot build the file correctly

### ISSUE THREAD

**Issue by chihchiehchen** [pawelswoboda/RAMA#23]
Hello,

Thanks for the great project. I am very interested in this subject. However, when I tried to build the code, I faced the following problem and cannot solve it. If you have any idea, please help!

In the beginning I begin with Cuda 11.2 and gcc-10.3， however I encountered the following problem:

> /usr/include/c++/10/chrono:473:154:`   required from here
> 
> /usr/include/c++/10/chrono:428:27: internal compiler error: Segmentation fault
>   428 |  _S_gcd(intmax_t __m, intmax_t __n) noexcept
>       |                           ^~~~~~
> Please submit a full bug report,
> with preprocessed source if appropriate.
> 
> 
> 

Therefore, I switch to gcc-9.3.0 and compile again, but still have the following problem:

> /root/RAMA/src/rama_py.cpp:` In function 'std::vector<at::Tensor> rama_torch(const at::Tensor&, const at::Tensor&, const at::Tensor&, const multicut_solver_options&)':
> 
> /root/RAMA/src/rama_py.cpp:48:44: error: cannot bind rvalue reference of type 'thrust::device_vector<int>&&' to lvalue of type 'thrust::device_vector<int>'
>    48 |     std::tie(node_mapping, lb) = rama_cuda(i, j, costs, opts, device);
>       |                                            ^
> In file included from /root/RAMA/src/rama_py.cpp:5:
> /root/RAMA/include/rama_cuda.h:9:87: note:   initializing argument 1 of 'std::tuple<thrust::device_vector<int, thrust::device_allocator<int> >, double> rama_cuda(thrust::device_vector<int>&&, thrust::device_vector<int>&&, thrust::device_vector<float>&&, const multicut_solver_options&, int)
> 

Do you have any suggestions? Thanks a lot!

**Comment by aabbas90** [comment]
Hi, Thanks for trying RAMA. I have fixed the issue and it should build. 

By they way I guess you are building flag `WITH_TORCH=ON` which is a bit brittle due to version conflicts. If it still does not build then try with `WITH_TORCH=OFF`. Afterwards if you would like to pass in GPU tensors instead of first copying them to CPU then use the approach described in: [gpu_pointers_usage](https://github.com/pawelswoboda/RAMA/blob/master/test/test_pytorch_pointers.py).

**Comment by chihchiehchen** [comment]
Hello,

Thanks for your help. Yes, as you said, I tried the flag WITH_TORCH=ON. After following your suggestion, the problem is solved but I encountered a new one (so sad...)

> [ 95%] Built target rama_cuda_test
> /home/ccchen/projects/RAMA/src/rama_py.cpp: In function ‘std::vector<at::Tensor> rama_torch(const at::Tensor&, const at::Tensor&, const at::Tensor&, const multicut_solver_options&)’:
> /home/ccchen/projects/RAMA/src/rama_py.cpp:50:65: warning: narrowing conversion of ‘node_mapping.thrust::device_vector<int>::<anonymous>.thrust::detail::vector_base<int, thrust::device_allocator<int> >::size()’ from ‘thrust::detail::vector_base<int, thrust::device_allocator<int> >::size_type’ {aka ‘long unsigned int’} to ‘long int’ [-Wnarrowing]
>    50 | rch::Tensor node_mapping_torch = at::empty({node_mapping.size()}, _i.options());
>       |                                             ~~~~~~~~~~~~~~~~~^~
> 
> /home/ccchen/projects/RAMA/src/rama_py.cpp:50:65: warning: narrowing conversion of ‘node_mapping.thrust::device_vector<int>::<anonymous>.thrust::detail::vector_base<int, thrust::device_allocator<int> >::size()’ from ‘thrust::detail::vector_base<int, thrust::device_allocator<int> >::size_type’ {aka ‘long unsigned int’} to ‘long int’ [-Wnarrowing]
> 

However, I build without the flag successfully. Thanks a lot! I learn a lot from this experience.  Thanks for your help!
