### ISSUE TITLE
Demo Code?

### ISSUE THREAD

**Issue by voidrank** [pawelswoboda/RAMA#27]
Hi @pawelswoboda 

This work is awesome! Do you have any script or hints for generating the cover segmentation figure?

Thanks!

**Comment by aabbas90** [comment]
Hi @voidrank,

Currently we do not have a demo script which takes an image and performs clustering. Specifically we assume that the graph and edge costs are given. However, give me a few days and I might be able to setup a simple demo.

**Comment by voidrank** [comment]
Hi @aabbas90 ,

Thanks!! I'm looking forward to the demo. I didn't quite get the idea of defining the cost of each edge. I find that the edge cost was defined in the previous paper on [panoptic segmentation](https://arxiv.org/abs/2106.03188#:~:text=Combinatorial%20Optimization%20for%20Panoptic%20Segmentation%3A%20A%20Fully%20Differentiable%20Approach,-Ahmed%20Abbas%2C%20Paul&text=We%20propose%20a%20fully%20differentiable,asymmetric%20multiway%20cut%20problem%20solver.), but I failed to locate the answer to my question in your paper.

**Comment by aabbas90** [comment]
I guess you already know but for completeness: 
The sample images were created by replacing line 
https://github.com/aabbas90/COPS/blob/de324dbb7199fddea8ad4f6b15ea658b06a1ce9c/affinityNet/panoptic_affinity/multicut_solvers.py#L157
by RAMA and not using node costs. For COPS the demo script is located at:
https://github.com/aabbas90/COPS/blob/camera_ready/affinityNet/run_demo.sh

Feel free to reopen if encountering further issues.
