### ISSUE TITLE
Found bad contractions for nn graph

### ISSUE THREAD

**Issue by leonsick** [pawelswoboda/RAMA#34]
Hi there!
First of all, thanks for open-sourcing this super cool algorithm! Also saw you guys are active wrt to issues, so I'll give it a shot :) 

I'm encountering the "Found bad contractions" Runtime Error. As input, I have a Nearest Neighbor graph representation consisting of source nodes, connecting nodes, and edge costs. I'm using a 10-NN graph with 3600 source nodes.
Here are the prints for .shape, .min() and .max()
```
source_nodes (36000,) 0 3599
connecting_nodes (36000,) 0 3599
costs (36000,) 0.0 1.0314723253250122
```
Inside source and connecting nodes, it looks something like this:
```
source_nodes [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
connecting_nodes [0, 60, 1, 61, 120, 2, 121, 62, 122, 3, 1, 61, 2, 0, 60, 62, 121, 3, 120, 122]
```

For this case, RAMA works just fine without any error, and produces 0s for all nodes (as expected).

But when I then normalize the costs with mean 0 and std 1, my range is shifted to the negative (-1 to 1), causing the error.
I made sure that all vertices of nodes connect to themselves (e.g node 0 to 0) have a cost of 0.0.

I've tried to look at the implementation and traced back the error to a diagonal assertion. Can you maybe help here what I'm doing wrong?

Here is some code that might help:

```
source_nodes = np.repeat(np.arange(neigh_dist.shape[0]), repeats=args.k_knn).tolist()
connecting_nodes = nn.tolist()
costs = neigh_dist.reshape(-1)

costs = (costs - np.mean(costs)) / np.std(costs).astype(np.float32).tolist()

...

res = rama_py.rama_cuda(source_nodes, connecting_nodes, costs, opts)
```

Thanks in advance!
Leon

**Comment by aabbas90** [comment]
Hi,

I would recommend the following

1. Remove diagonal edges.
2. Make sure only one of the edge (i, j) and (j, i) exists. 

For example both can be done by

```
valid_edge_mask = source_nodes < connecting_nodes
i = source_nodes[valid_edge_mask]
j = connecting_nodes[valid_edge_mask]
c = costs[valid_edge_mask]
```
please let me know if the error still occurs. In this case please also share the data containing `i, j, c`

**Comment by leonsick** [comment]
Thanks for the help!
After some more experimentation, I'm now excluding self-edges, and now RAMA works flawlessly! Amazing stuff, thanks a lot :)

**Comment by leonsick** [comment]
Thanks for the help!
After some more experimentation, I'm now excluding self-edges, and now RAMA works flawlessly! Amazing stuff, thanks a lot :)
